#!/usr/bin/env bash
# .claude/scripts/session-prefetch.sh
#
# Fires on SessionStart. Writes .claude/session-state.md with a snapshot of the
# six orient-step inputs from CLAUDE.md §3 Step 1, so the model can read ONE
# file instead of issuing six tool calls at the start of every heartbeat.
#
# Safe to fail silently — the heartbeat's Step 1 fallback is to gather the
# same information via live tool calls. This is a speed/context optimisation,
# not a correctness dependency.

set +e  # keep going even if a command fails; this is best-effort

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="$REPO_ROOT/.claude/session-state.md"
TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Run `npm install` for root + dashboard/ so `npm test` works out-of-the-box in
# fresh remote sessions (fresh clones have no node_modules/). Short-circuits
# when node_modules/ already exists — warm sessions skip the install entirely
# and record "already warm" in the summary. Per Issue #61; Issue #87 resolved
# by bumping react/react-dom off the RC pin to stable ^19.0.0, so
# --legacy-peer-deps is no longer needed. Exit code of each install is
# captured so the summary shows success/fail unambiguously.
prefetch_install() {
  # $1 = label ("[root]" / "[dashboard/]"), $2 = abs dir, $3.. = extra flags
  local label="$1" dir="$2"; shift 2
  if [ -d "$dir/node_modules" ]; then
    printf '%s exit=0 (already warm — skipped npm install)\n' "$label"
    return
  fi
  local out rc
  # `set -o pipefail` scoped to this subshell so the exit code reflects
  # `npm install` rather than `tail`.
  out="$(set -o pipefail; cd "$dir" && npm install --no-audit --no-fund "$@" 2>&1 | tail -5)"
  rc=$?
  printf '%s exit=%d\n%s\n' "$label" "$rc" "$out"
}

ROOT_INSTALL_LOG="$(prefetch_install '[root]'       "$REPO_ROOT")"
DASH_INSTALL_LOG="$(prefetch_install '[dashboard/]' "$REPO_ROOT/dashboard")"

{
  echo "# Session Prefetch — $TS"
  echo
  echo "_Generated by \`.claude/scripts/session-prefetch.sh\` on SessionStart._"
  echo "_Used by CLAUDE.md §3 Step 1 — read this file first; fall back to live tool calls if stale or missing._"
  echo
  echo "## Dependency install summary"
  echo '```'
  echo "[root]"
  echo "${ROOT_INSTALL_LOG:-<no output>}"
  echo
  echo "[dashboard/]"
  echo "${DASH_INSTALL_LOG:-<no output>}"
  echo '```'
  echo
  echo "## git status --short"
  echo '```'
  (cd "$REPO_ROOT" && git status --short 2>&1 | head -50)
  echo '```'
  echo
  echo "## git log --oneline -10"
  echo '```'
  (cd "$REPO_ROOT" && git log --oneline -10 2>&1)
  echo '```'
  echo
  echo "## gh issue list --state open --limit 30"
  echo '```'
  (cd "$REPO_ROOT" && gh issue list --state open --limit 30 2>&1 | head -40)
  echo '```'
  echo
  echo "## Latest run report"
  LATEST="$(cd "$REPO_ROOT" && ls -1 reports/run-*-summary.md 2>/dev/null | sort -V | tail -1)"
  if [ -n "$LATEST" ]; then
    echo "**File**: \`$LATEST\`"
    echo
    echo "**First line**: $(head -1 "$REPO_ROOT/$LATEST" 2>/dev/null)"
  else
    echo "_(no run-*-summary.md found)_"
  fi
  echo
  echo "## Last 5 Decision IDs"
  echo '```'
  (cd "$REPO_ROOT" && grep -oE 'D-[0-9]{8}-[0-9]{3}' decision-log.md 2>/dev/null | tail -5)
  echo '```'
  echo
  echo "## Dev-Q&A.md — Open Questions"
  if [ -f "$REPO_ROOT/Docs/Plans/Dev-Q&A.md" ]; then
    (cd "$REPO_ROOT" && awk '/^## Open Questions/,/^---/' 'Docs/Plans/Dev-Q&A.md' 2>/dev/null | head -80)
  else
    echo "_(Docs/Plans/Dev-Q&A.md not found)_"
  fi
} > "$OUT" 2>&1

exit 0
