#!/usr/bin/env bash
# .claude/scripts/session-prefetch.sh
#
# Fires on SessionStart. Writes .claude/session-state.md with a snapshot of the
# six orient-step inputs from CLAUDE.md §3 Step 1, so the model can read ONE
# file instead of issuing six tool calls at the start of every heartbeat.
#
# Safe to fail silently — the heartbeat's Step 1 fallback is to gather the
# same information via live tool calls. This is a speed/context optimisation,
# not a correctness dependency.

set +e  # keep going even if a command fails; this is best-effort

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="$REPO_ROOT/.claude/session-state.md"
TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Run `npm install` for root + dashboard/ so `npm test` works out-of-the-box in
# fresh remote sessions (fresh clones have no node_modules/). Idempotent; a
# warm install is effectively a no-op. Dashboard needs --legacy-peer-deps due
# to the React 19 RC / @testing-library/react peer conflict (D-20260418-001;
# `overrides` fix is intermittently absent on main — see follow-up Issue).
# Output is captured for the summary block below. Per Issue #61.
ROOT_INSTALL_LOG="$(cd "$REPO_ROOT" && npm install --no-audit --no-fund 2>&1 | tail -5)"
DASH_INSTALL_LOG="$(cd "$REPO_ROOT/dashboard" && npm install --no-audit --no-fund --legacy-peer-deps 2>&1 | tail -5)"

{
  echo "# Session Prefetch — $TS"
  echo
  echo "_Generated by \`.claude/scripts/session-prefetch.sh\` on SessionStart._"
  echo "_Used by CLAUDE.md §3 Step 1 — read this file first; fall back to live tool calls if stale or missing._"
  echo
  echo "## Dependency install summary"
  echo '```'
  echo "[root]"
  echo "${ROOT_INSTALL_LOG:-<no output>}"
  echo
  echo "[dashboard/]"
  echo "${DASH_INSTALL_LOG:-<no output>}"
  echo '```'
  echo
  echo "## git status --short"
  echo '```'
  (cd "$REPO_ROOT" && git status --short 2>&1 | head -50)
  echo '```'
  echo
  echo "## git log --oneline -10"
  echo '```'
  (cd "$REPO_ROOT" && git log --oneline -10 2>&1)
  echo '```'
  echo
  echo "## gh issue list --state open --limit 30"
  echo '```'
  (cd "$REPO_ROOT" && gh issue list --state open --limit 30 2>&1 | head -40)
  echo '```'
  echo
  echo "## Latest run report"
  LATEST="$(cd "$REPO_ROOT" && ls -1 reports/run-*-summary.md 2>/dev/null | sort -V | tail -1)"
  if [ -n "$LATEST" ]; then
    echo "**File**: \`$LATEST\`"
    echo
    echo "**First line**: $(head -1 "$REPO_ROOT/$LATEST" 2>/dev/null)"
  else
    echo "_(no run-*-summary.md found)_"
  fi
  echo
  echo "## Last 5 Decision IDs"
  echo '```'
  (cd "$REPO_ROOT" && grep -oE 'D-[0-9]{8}-[0-9]{3}' decision-log.md 2>/dev/null | tail -5)
  echo '```'
  echo
  echo "## Dev-Q&A.md — Open Questions"
  if [ -f "$REPO_ROOT/Docs/Plans/Dev-Q&A.md" ]; then
    (cd "$REPO_ROOT" && awk '/^## Open Questions/,/^---/' 'Docs/Plans/Dev-Q&A.md' 2>/dev/null | head -80)
  else
    echo "_(Docs/Plans/Dev-Q&A.md not found)_"
  fi
} > "$OUT" 2>&1

exit 0
